services:
  strapi:
    build:
      context: .
      target: development
    ports:
      - "3002:1337"
    volumes:
      - ./.tmp:/app/.tmp
      - ./public/uploads:/app/public/uploads
      - ./src:/app/src
      - ./config:/app/config
    env_file: .env
    restart: unless-stopped
    command: npm run strapi -- develop
